# Configuration file for chip generation
dataset:
  version: "v0.40"

aoi:
  version: "v0.30"

working_dir: "/home/benchuser/data/v0.40"
output_dir: "/home/benchuser/final_data"
# Metadata
metadata:
  file: "metadata_df.csv"

excluded_aoi_indices: 
 - 12
 - 25
 - 46
 - 60
 - 81
 - 153

# Sentinel-2 (S2) settings
sentinel_2:
  collection: "sentinel-2-l2a"
  time_ranges:
    - "2023-01-01/2023-03-31"  # JFM (Jan-Feb-Mar)
    - "2023-04-01/2023-06-30"  # AMJ (Apr-May-Jun)
    - "2023-07-01/2023-09-30"  # JAS (Jul-Aug-Sep)
    - "2023-10-01/2023-12-31"  # OND (Oct-Nov-Dec)
  cloud_cover: 50  # Maximum allowed cloud cover percentage
  nodata_pixel_percentage : 5 # Maximum missing data percentage
  bands:
  - "B01"
  - "B02"
  - "B03"
  - "B04"
  - "B05"
  - "B06"
  - "B07"
  - "B08"
  - "B8A"
  - "B09"
  - "B10"
  - "B11"
  - "B12"
  - "SCL"
  cloud_band: "SCL"
  resolution: 10  # Spatial resolution in meters
  native_crs: True

# Sentinel-1 (S1) settings
sentinel_1:
  collection: "sentinel-1-rtc"
  nodata_pixel_percentage : 5 # Maximum missing data percentage
  bands: ["vv", "vh"]  # VV, VH
  resolution: 10  # Spatial resolution in meters
  native_crs: False # False gets crs of S2, True gets crs of first Landsat scene
                
# Landsat-8 (L8) settings
landsat:
  collection: "landsat-c2-l2"
  platforms: ["landsat-8", "landsat-9"]
  cloud_cover: 50  # Maximum allowed cloud cover percentage
  # landsat does not have a nodata pixel percentage property
  bands:
  - "coastal"    # Coastal/Aerosol (Band 1)
  - "blue"       # Blue (Band 2)
  - "green"      # Green (Band 3)
  - "red"        # Red (Band 4)
  - "nir08"      # Near Infrared (NIR, Band 5)
  - "swir16"     # Shortwave Infrared 1 (SWIR1, Band 6)
  - "swir22"     # Shortwave Infrared 2 (SWIR2, Band 7)
  - "pan"        # Panchromatic (Band 8)
  - "cirrus"     # Cirrus (Band 9)
  - "tir10"      # Thermal Infrared 1 (TIR1, Band 10)
  - "tir11"      # Thermal Infrared 2 (TIR2, Band 11)
  - "qa_pixel"   # Quality Assessment Pixel Mask  # Blue, Green, Red, NIR, SWIR1, SWIR2
  cloud_band: "qa_pixel"
  resolution: 10  # Spatial resolution in meters
  native_crs: False # False gets crs of S2, True gets crs of first Landsat scene

dem:
  collection: "cop-dem-glo-30"
  year: "2021-01-02/2021-12-31"
  resolution: 10  # Spatial resolution in meters
  native_crs: False # False gets crs of S2

# Land Cover (LC) settings
land_cover:
  collection: "io-lulc-annual-v02"
  year: "2023-01-02/2023-12-31" # Year for the land cover dataset
  # sampling_factor is used to even out samples of different land cover classes
  # it is equal to the count of the largest category divided by the count of the smallest category in the final dataset
  # sampling_factor of 1 forces equal distribution for all classes
  sampling_factor: 5 # int >= 1; leave blank for no class redistribution
  
# Chip settings
chips:
  sample_size: 64  # Size of samples for homogeneity check
  chip_size: 64  # Final chip size for training data

