# Configuration file for chip generation
dataset:
  version: "v0.50.1"

aoi:
  version: "v0.40"
  include_indices:
  exclude_indices:

directory:
  working: "/app/data/interim"
  output: "/app/data/processed"

log_errors: true

# Sentinel-2 (S2) settings
sentinel_2:
  collection: "sentinel-2-l2a"
  time_ranges:
    - "2023-01-01/2023-03-31" # (Jan-Feb-Mar)
    - "2023-04-01/2023-06-30" # (Apr-May-Jun)
    - "2023-07-01/2023-09-30" # (Jul-Aug-Sep)
    - "2023-10-01/2023-12-31" # (Oct-Nov-Dec)
  cloud_cover: 30  # Maximum allowed cloud cover percentage in scene
  nodata_pixel_percentage : 5 # Maximum missing data percentage in scene
  bands:
  - "B01"
  - "B02"
  - "B03"
  - "B04"
  - "B05"
  - "B06"
  - "B07"
  - "B08"
  - "B8A"
  - "B09"
  #- "B10"
  - "B11"
  - "B12"
  - "SCL"
  cloud_band: "SCL"
  resolution: 10  # Spatial resolution in meters
  native_crs: true
  fill_na: false
  na_value: -999 
  dtype: "int16"

# Sentinel-1 (S1) settings
sentinel_1:
  delta_days: 12
  collection: "sentinel-1-rtc"
  nodata_pixel_percentage : 5 # Maximum missing data percentage in scene
  bands: ["vv", "vh"]  # VV, VH
  resolution: 10  # Spatial resolution in meters
  native_crs: false # False gets crs of S2, True gets crs of first Landsat scene              
  fill_na: false
  na_value: -999 
  dtype: "float32"

# Landsat-8 (L8) and Landsat-9 (L9) settings
landsat:
  delta_days: 91 # get the full season for landsat
  collection: "landsat-c2-l2"
  platforms: ["landsat-8", "landsat-9"]
  cloud_cover: 50  # Maximum allowed cloud cover percentage in scene
  # landsat does not have a nodata pixel percentage property
  bands:
  - "coastal"    # Coastal/Aerosol (Band 1)
  - "blue"       # Blue (Band 2)
  - "green"      # Green (Band 3)
  - "red"        # Red (Band 4)
  - "nir08"      # Near Infrared (NIR, Band 5)
  - "swir16"     # Shortwave Infrared 1 (SWIR1, Band 6)
  - "swir22"     # Shortwave Infrared 2 (SWIR2, Band 7)
  #- "pan"        # Panchromatic (Band 8)
  #- "cirrus"     # Cirrus (Band 9)
  #- "tir10"      # Thermal Infrared 1 (TIR1, Band 10)
  #- "tir11"      # Thermal Infrared 2 (TIR2, Band 11)
  - "qa_pixel"   # Quality Assessment Pixel Mask  # Blue, Green, Red, NIR, SWIR1, SWIR2
  cloud_band: "qa_pixel"
  resolution: 30  # Spatial resolution in meters
  native_crs: False # False gets crs of S2, True gets crs of first Landsat scene
  fill_na: false
  na_value: -999
  dtype: float32

dem:
  collection: "cop-dem-glo-30"
  year: "2021-01-02/2021-12-31"
  resolution: 30  # Spatial resolution in meters
  native_crs: False # False gets crs of S2
  fill_na: false
  na_value: -999
  dtype: float32

# Land Cover (LC) settings
land_cover:
  collection: "io-lulc-annual-v02"
  year: "2023-01-02/2023-12-31" # Year for the land cover dataset
  resolution: 10
  native_crs: False # False gets crs of S2
  # sampling_factor is used to even out samples of different land cover classes
  # it is equal to the count of the largest category divided by the count of the smallest category in the final dataset
  # sampling_factor of 1 forces equal distribution for all classes
  sampling_factor: # int >= 1; leave blank for no class redistribution
  fill_na: false
  na_value: 0
  dtype: int8
  
# Chip settings
chips:
  sample_size: 960  # Size of samples for homogeneity check in meters
  chip_size: 960  # Final chip size for training data in meters

