[workspace]
name = "gelos-lc-datagen"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
pystac-client = "0.7.*"
planetary-computer = "1.0.*"
leafmap = "0.38.*"
matplotlib = "*"
dask = "2024.9.*"
dask-labextension = "*"
distributed = "2024.9.*"
rioxarray = "0.17.*"
stackstac = "0.5.*"
numpy = "<2.0"
tifffile = "2024.9.*"
localtileserver = "*"
jupyter-server-proxy = "*"
s3fs = "*"
